In [26]:
import pandas as pd
import requests

In [45]:
url = "https://www.omjaa.com/wp-json/wc/store/v1/products?per_page=50"
response =requests.get(url)
data = response.json()
print(type(data))
print(len(data))

<class 'list'>
50

In [28]:
data[0]

{'id': 26574,
 'name': 'Mantrit (Energized) Parad Goli, Original &#038; Genuine (Set of 7)- 10 mm &#8211; 35 Gram apprx',
 'slug': 'mantrit-energized-parad-goli-original-genuine-set-of-7-10-mm-35-gram-apprx',
 'parent': 0,
 'type': 'simple',
 'variation': '',
 'permalink': 'https://www.omjaa.com/product/mantrit-energized-parad-goli-original-genuine-set-of-7-10-mm-35-gram-apprx/',
 'sku': 'S03322',
 'short_description': '<ul>\n<li><span style="font-size: 12px;color: #808080"><strong><span class="s1">It brings prosperity and wealth in the house. </span></strong></span></li>\n<li><span style="font-size: 12px;color: #808080"><strong><span class="s1">By keeping this Mercury Goli, you will not face any shortage of food,or clothes in your house. </span></strong></span></li>\n<li><span style="font-size: 12px;color: #808080"><strong><span class="s1">Parad brings peace and harmony in your house.</span></strong></span></li>\n</ul>',
 'description': '<p><span style="font-size: 16px;color: #ff6600"><strong><span class="s1">Product Origin : India</span></strong></span></p>\n<p><span style="font-size: 20px"><strong>Parad Goli</strong></span></p>\n<p><span style="font-size: 18px"><strong><span class="s1">It brings prosperity and wealth in the house. By keeping this Mercury Goli, you will not face any shortage of food,or clothes in your house. Parad brings peace and harmony in your house.</span></strong></span></p>',
 'on_sale': True,
 'prices': {'price': '96000',
  'regular_price': '148000',
  'sale_price': '96000',
  'price_range': None,
  'currency_code': 'INR',
  'currency_symbol': '₹',
  'currency_minor_unit': 2,
  'currency_decimal_separator': '.',
  'currency_thousand_separator': ',',
  'currency_prefix': '₹',
  'currency_suffix': ''},
 'price_html': '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#8377;</span>1,480.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#8377;</span>960.00</span></ins> <small class="woocommerce-price-suffix">inc.GST</small>',
 'average_rating': '0',
 'review_count': 0,
 'images': [{'id': 26575,
   'src': 'https://www.omjaa.com/wp-content/uploads/2026/05/1.jpg',
   'thumbnail': 'https://www.omjaa.com/wp-content/uploads/2026/05/1-300x300.jpg',
   'srcset': 'https://www.omjaa.com/wp-content/uploads/2026/05/1.jpg 800w, https://www.omjaa.com/wp-content/uploads/2026/05/1-600x600.jpg 600w, https://www.omjaa.com/wp-content/uploads/2026/05/1-768x768.jpg 768w, https://www.omjaa.com/wp-content/uploads/2026/05/1-640x640.jpg 640w, https://www.omjaa.com/wp-content/uploads/2026/05/1-400x400.jpg 400w, https://www.omjaa.com/wp-content/uploads/2026/05/1-560x560.jpg 560w, https://www.omjaa.com/wp-content/uploads/2026/05/1-367x367.jpg 367w',
   'sizes': '(max-width: 800px) 100vw, 800px',
   'name': '1',
   'alt': ''},
  {'id': 26577,
   'src': 'https://www.omjaa.com/wp-content/uploads/2026/05/3.jpg',
   'thumbnail': 'https://www.omjaa.com/wp-content/uploads/2026/05/3-300x300.jpg',
   'srcset': 'https://www.omjaa.com/wp-content/uploads/2026/05/3.jpg 800w, https://www.omjaa.com/wp-content/uploads/2026/05/3-600x600.jpg 600w, https://www.omjaa.com/wp-content/uploads/2026/05/3-768x768.jpg 768w, https://www.omjaa.com/wp-content/uploads/2026/05/3-640x640.jpg 640w, https://www.omjaa.com/wp-content/uploads/2026/05/3-400x400.jpg 400w, https://www.omjaa.com/wp-content/uploads/2026/05/3-560x560.jpg 560w, https://www.omjaa.com/wp-content/uploads/2026/05/3-367x367.jpg 367w',
   'sizes': '(max-width: 800px) 100vw, 800px',
   'name': '3',
   'alt': ''},
  {'id': 26576,
   'src': 'https://www.omjaa.com/wp-content/uploads/2026/05/2.jpg',
   'thumbnail': 'https://www.omjaa.com/wp-content/uploads/2026/05/2-300x300.jpg',
   'srcset': 'https://www.omjaa.com/wp-content/uploads/2026/05/2.jpg 800w, https://www.omjaa.com/wp-content/uploads/2026/05/2-600x600.jpg 600w, https://www.omjaa.com/wp-content/uploads/2026/05/2-768x768.jpg 768w, https://www.omjaa.com/wp-content/uploads/2026/05/2-640x640.jpg 640w, https://www.omjaa.com/wp-content/uploads/2026/05/2-400x400.jpg 400w, https://www.omjaa.com/wp-content/uploads/2026/05/2-560x560.jpg 560w, https://www.omjaa.com/wp-content/uploads/2026/05/2-367x367.jpg 367w',
   'sizes': '(max-width: 800px) 100vw, 800px',
   'name': '2',
   'alt': ''}],
 'categories': [{'id': 107,
   'name': 'Parad',
   'slug': 'parad',
   'link': 'https://www.omjaa.com/product-category/spiritual/parad/'},
  {'id': 103,
   'name': 'Spiritual',
   'slug': 'spiritual',
   'link': 'https://www.omjaa.com/product-category/spiritual/'}],
 'tags': [{'id': 2387,
   'name': 'Buy online Omjaa',
   'slug': 'buy-online-omjaa',
   'link': 'https://www.omjaa.com/product-tag/buy-online-omjaa/'},
  {'id': 2463,
   'name': 'Natural Parad Goli',
   'slug': 'natural-parad-goli',
   'link': 'https://www.omjaa.com/product-tag/natural-parad-goli/'},
  {'id': 2464,
   'name': 'Original Parad Goli',
   'slug': 'original-parad-goli',
   'link': 'https://www.omjaa.com/product-tag/original-parad-goli/'}],
 'attributes': [],
 'variations': [],
 'has_options': False,
 'is_purchasable': True,
 'is_in_stock': True,
 'is_on_backorder': False,
 'low_stock_remaining': None,
 'sold_individually': False,
 'add_to_cart': {'text': 'Add to cart',
  'description': 'Add &ldquo;Mantrit (Energized) Parad Goli, Original &#038; Genuine (Set of 7)- 10 mm &#8211; 35 Gram apprx&rdquo; to your cart',
  'url': '?add-to-cart=26574',
  'minimum': 1,
  'maximum': 4,
  'multiple_of': 1},
 'extensions': {}}

In [46]:
#Convert JSON to DataFrame
df = pd.json_normalize(data)
#or 
df =pd.DataFrame(data)
# print(df) #it didnot reprasent  data set in table formet
df  # it  reprasent  data set in table formet

,id,name,slug,parent,type,variation,permalink,sku,short_description,description,...,attributes,variations,has_options,is_purchasable,is_in_stock,is_on_backorder,low_stock_remaining,sold_individually,add_to_cart,extensions
0,26574,"Mantrit (Energized) Parad Goli, Original &#038...",mantrit-energized-parad-goli-original-genuine-...,0,simple,,https://www.omjaa.com/product/mantrit-energize...,S03322,"<ul>\n<li><span style=""font-size: 12px;color: ...","<p><span style=""font-size: 16px;color: #ff6600...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
1,26528,Mantrit Vastu Brass Brahmasthan Plate with 9 P...,abhimantrit-vastu-brass-brahmasthan-plate-with...,0,simple,,https://www.omjaa.com/product/abhimantrit-vast...,S03321,"<ul data-start=""670"" data-end=""916"">\n<li data...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
2,26518,Mantrit Brass Manjusha Box for Vastu – Treasur...,abhimantrit-brass-manjusha-box-for-vastu-treas...,0,simple,,https://www.omjaa.com/product/abhimantrit-bras...,S03320,"<ul>\n<li data-section-id=""itgds9"" data-start=...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
3,26511,Mantrit Brass Nabhi Set for Vastu Correction &...,abhimantrit-brass-nabhi-set-for-vastu-correcti...,0,simple,,https://www.omjaa.com/product/abhimantrit-bras...,S03319,"<ul>\n<li><span style=""font-size: 12px;color: ...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
4,26480,Natural Amethyst Crystal Cave (28.7 Kg) – 15 I...,natural-amethyst-crystal-cave-28-7-kg-15-inch-...,0,simple,,https://www.omjaa.com/product/natural-amethyst...,S03318,"<ul class=""i8Z77e"">\n<li class=""TrT0Xe""><span ...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
5,26450,Mantrit 4 Mukhi Rudraksha Nepali 28mm Rare Bea...,mantrirt-4-mukhi-rudraksha-nepali-29-8mm-rare-...,0,simple,,https://www.omjaa.com/product/mantrirt-4-mukhi...,S03317,"<ul>\n<li><span style=""color: #808080""><strong...","<p><strong><span style=""color: #ff6600"">Produc...",...,"[{'id': 0, 'name': 'select', 'taxonomy': None,...",[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
6,26408,Mantrit Rose Quartz Ducks &#8211; 89 Gram | Lo...,mantrit-rose-quartz-ducks-89-gram-love-relatio...,0,simple,,https://www.omjaa.com/product/mantrit-rose-qua...,S03316,"<ul>\n<li data-path-to-node=""1,0,0""><span styl...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
7,26402,Mantrit Rose Quartz Ducks &#8211; 107 Gram | L...,abhimantrit-rose-quartz-ducks-love-relationshi...,0,simple,,https://www.omjaa.com/product/abhimantrit-rose...,S03315,"<ul>\n<li data-path-to-node=""1,0,0""><span styl...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
8,26393,Natural Raw Moonstone Chunks – Rough Healing C...,natural-raw-moonstone-chunks-rough-healing-cry...,0,simple,,https://www.omjaa.com/product/natural-raw-moon...,S03314,"<p><span style=""color: #808080""><strong><span ...",<h2>Natural Raw Moonstone Chunks 140 Grams app...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
9,26391,Product,product-2,0,simple,,https://www.omjaa.com/product/product-2/,,,,...,[],[],False,False,True,False,None,False,"{'text': 'Read more', 'description': 'Read mor...",{}
10,26389,Product,product,0,simple,,https://www.omjaa.com/product/product/,,,,...,[],[],False,False,True,False,None,False,"{'text': 'Read more', 'description': 'Read mor...",{}
11,26374,Original Tiger Eye Shivling Mantrit (Energized...,original-tiger-eye-shivling-mantrit-energized-...,0,simple,,https://www.omjaa.com/product/original-tiger-e...,S03312,"<ul>\n<li><span class=""a-list-item"" style=""col...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
12,26364,Genuine Labradorite Hanuman ji Idol Mantrit (E...,genuine-labradorite-hanuman-ji-idol-mantrit-en...,0,simple,,https://www.omjaa.com/product/genuine-labrador...,S03311,"<ul>\n<li class=""LGOjhe"" role=""heading"" data-a...","<h2 data-thread-perm-id=""thread-f:168987564878...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
13,26351,Mantrit 5 Mukhi Rudraksha Kanthi Mala 54+1 Bea...,mantrit-5-mukhi-rudraksha-kanthi-mala-541-bead...,0,simple,,https://www.omjaa.com/product/mantrit-5-mukhi-...,S03310,"<ul>\n<li><span style=""font-size: 11px;color: ...","<h5><span style=""color: #ff6600"">Product Origi...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
14,26330,Mantrit 5 Mukhi Rudraksha (Nepali) Big Rare Be...,mantrit-5-mukhi-rudraksha-nepali-big-rare-bead...,0,simple,,https://www.omjaa.com/product/mantrit-5-mukhi-...,S03308,"<ul>\n<li><span style=""color: #808080""><strong...","<p><strong><span style=""color: #ff6600"">Produc...",...,"[{'id': 0, 'name': 'Select', 'taxonomy': None,...",[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
15,26277,Karungali Mala (Ebony Wood Mala) – Natural Bla...,karungali-mala-ebony-wood-mala-natural-blackwo...,0,simple,,https://www.omjaa.com/product/karungali-mala-e...,S03307,"<p><span style=""color: #333333""><strong><span ...","<p><span style=""font-size: 18px""><strong><span...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
16,26126,Original Big Green Aventurine Raw Stone &#8211...,original-big-green-aventurine-raw-stone-certif...,0,variable,,https://www.omjaa.com/product/original-big-gre...,,"<ul>\n<li><span style=""color: #808080""><strong...","<h1 class=""title style-scope ytd-video-primary...",...,"[{'id': 0, 'name': 'WEIGHT', 'taxonomy': None,...","[{'id': 26132, 'attributes': [{'name': 'WEIGHT...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
17,26117,Certified Moonstone Bracelet – Embrace Serenit...,certified-moonstone-bracelet-embrace-serenity-...,0,simple,,https://www.omjaa.com/product/certified-moonst...,S03297,"<ul>\n<li><span style=""color: #808080""><strong...",<h2>Certified Moonstone Bracelet – Embrace Ser...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
18,26098,Mantrit Pyrite Frame with Gayatri Mantra – Ele...,pyrite-frame-with-gayatri-mantra-elevate-your-...,0,variable,,https://www.omjaa.com/product/pyrite-frame-wit...,,"<ul>\n<li><strong><span style=""font-size: 12px...","<p><strong style=""color: #ff6600""><span class=...",...,"[{'id': 0, 'name': 'Quantity', 'taxonomy': Non...","[{'id': 26099, 'attributes': [{'name': 'Quanti...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
19,26091,Natural Chandra Mani (Mukta Mani) 25 Carat in ...,natural-chandra-mani-mukta-mani-25-carat-in-si...,0,variable,,https://www.omjaa.com/product/natural-chandra-...,,"<div class=""wDYxhc"" lang=""en-IN"" data-md=""61"">...","<h2 data-thread-perm-id=""thread-f:170854302764...",...,"[{'id': 0, 'name': 'select', 'taxonomy': None,...","[{'id': 26092, 'attributes': [{'name': 'select...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
20,26085,Natural Chandra Mani (Mukta Mani) 30 Carat in ...,natural-chandra-mani-mukta-mani-30-carat-in-si...,0,variable,,https://www.omjaa.com/product/natural-chandra-...,,"<div class=""wDYxhc"" lang=""en-IN"" data-md=""61"">...","<h2 data-thread-perm-id=""thread-f:170854302764...",...,"[{'id': 0, 'name': 'select', 'taxonomy': None,...","[{'id': 26086, 'attributes': [{'name': 'select...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
21,26079,"Natural Ganesh Shankh 8cm Approx – Mantrit , G...",natural-ganesh-shankh-8cm-approx-mantrit-genui...,0,simple,,https://www.omjaa.com/product/natural-ganesh-s...,S03290,"<ul data-spread=""false"" data-pm-slice=""3 1 []""...","<h2 data-thread-perm-id=""thread-f:171368921599...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
22,26064,Authentic Golden White Shukra Mani Abhimantrit...,authentic-golden-white-shukra-mani-abhimantrit...,0,variable,,https://www.omjaa.com/product/authentic-golden...,,"<ul>\n<li><span style=""color: #808080;font-siz...","<p><strong><span style=""color: #ff6600""><span ...",...,"[{'id': 0, 'name': 'Carats', 'taxonomy': None,...","[{'id': 26066, 'attributes': [{'name': 'Carats...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
23,26043,Triangle Pyrite Frame 9 Inch for Home Decor &#...,original-9-inch-pyrite-triangle-frame-for-home...,0,simple,,https://www.omjaa.com/product/original-9-inch-...,S03284,"<div class=""flex max-w-full flex-col flex-grow...","<p><strong style=""color: #ff6600""><span class=...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
24,26025,Original Cinnamon Essential Oil (Dalchini Tel)...,original-cinnamon-essential-oil-dalchini-tel-a...,0,variable,,https://www.omjaa.com/product/original-cinnamo...,,"<div class=""flex max-w-full flex-col flex-grow...","<h1 class=""title style-scope ytd-video-primary...",...,"[{'id': 0, 'name': 'ML', 'taxonomy': None, 'ha...","[{'id': 26029, 'attributes': [{'name': 'ML', '...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
25,26011,Very Rare Nepali 5 Mukhi Rudraksha Mala Origin...,very-rare-nepali-5-mukhi-rudraksha-mala-origin...,0,variable,,https://www.omjaa.com/product/very-rare-nepali...,,"<ul>\n<li><span style=""color: #808080;font-siz...","<p class=""p1""><span style=""color: #000000;font...",...,"[{'id': 0, 'name': 'SELECT', 'taxonomy': None,...","[{'id': 26012, 'attributes': [{'name': 'SELECT...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
26,26000,Mach Mani (Fish Pearl) &#038; Abhimantrit Natu...,mach-mani-fish-pearl-abhimantrit-natural-brown...,0,simple,,https://www.omjaa.com/product/mach-mani-fish-p...,S03277,"<ul>\n<li class=""co8aDb gsrt"" role=""heading""><...","<p><strong><span style=""font-size: 16px;color:...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
27,25924,Certified Supreme Quality Golden Pyrite Raw St...,certified-supreme-quality-golden-pyrite-raw-st...,0,variable,,https://www.omjaa.com/product/certified-suprem...,,"<ul>\n<li><span style=""font-size: 12px;color: ...","<div class=""nH V8djrc byY"">\n<div class=""nH"">\...",...,"[{'id': 0, 'name': 'WEIGHT', 'taxonomy': None,...","[{'id': 25931, 'attributes': [{'name': 'WEIGHT...",True,True,True,False,None,False,"{'text': 'Select options', 'description': 'Sel...",{}
28,25923,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,natural-cow-dung-dhoop-cow-dung-havan-cups-pac...,0,simple,,https://www.omjaa.com/product/natural-cow-dung...,S03270,"<ul>\n<li><span style=""color: #808080""><strong...","<h1><span style=""font-size: 16px;color: #ff660...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
29,25922,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,natural-cow-dung-dhoop-cow-dung-havan-cups-pac...,0,simple,,https://www.omjaa.com/product/natural-cow-dung...,S03269,"<ul>\n<li><span style=""color: #808080""><strong...","<h1><span style=""font-size: 16px;color: #ff660...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
30,25914,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,natural-cow-dung-dhoop-cow-dung-havan-cups-pac...,0,simple,,https://www.omjaa.com/product/natural-cow-dung...,S03268,"<ul>\n<li><span style=""color: #808080""><strong...","<h1><span style=""font-size: 16px;color: #ff660...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
31,25791,Original Zibu Coin Bracelet With Multi Stone P...,original-zibu-coin-bracelet-with-multi-stone-p...,0,simple,,https://www.omjaa.com/product/original-zibu-co...,S03263,"<ul>\n<li><strong><span style=""font-size: 11px...",<h2>Original Zibu Coin Bracelet With Multi Sto...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
32,25735,Lab -Certified Natural Green Aventurine 5.25 c...,lab-certified-natural-green-aventurine-5-25-ca...,0,simple,,https://www.omjaa.com/product/lab-certified-na...,S03258,"<ul>\n<li><span style=""color: #808080;font-siz...","<h2 id="":1y"" class=""hP"" data-thread-perm-id=""t...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
33,25696,Mantrit (Energized) Vastu Maha Yantra,abhimantrit-vastu-maha-yantra,0,simple,,https://www.omjaa.com/product/abhimantrit-vast...,S03257,"<ul>\n<li><span style=""font-size: 11px;color: ...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
34,25693,Mantrit (Energized) Sarva Badha Nivaran Yantra,abhimantrit-sarva-badha-nivaran-yantra,0,simple,,https://www.omjaa.com/product/abhimantrit-sarv...,S03256,"<ul>\n<li><span style=""color: #999999""><strong...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
35,25678,Nature And Original Camphor (Kapoor) Oil – 10 ML,nature-and-original-camphor-kapoor-oil-10-ml,0,simple,,https://www.omjaa.com/product/nature-and-origi...,S03255,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
36,25676,X Chocolate Attar Fragrance Attar – 10 ML,x-chocolate-attar-fragrance-attar-10-ml,0,simple,,https://www.omjaa.com/product/x-chocolate-atta...,S03254,"<ul>\n<li><span style=""color: #999999""><strong...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
37,25675,Dior Premium Quality Fragrance Attar – 10 ML,dior-premium-quality-fragrance-attar-10-ml,0,simple,,https://www.omjaa.com/product/dior-premium-qua...,S03253,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
38,25673,Cigar Fragrance Attar – 10 ML,cigar-fragrance-attar-10-ml,0,simple,,https://www.omjaa.com/product/cigar-fragrance-...,S03252,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
39,25670,Golden Dust Fragrance Attar For Gold Personali...,golden-dust-fragrance-attar-for-gold-personali...,0,simple,,https://www.omjaa.com/product/golden-dust-frag...,S03251,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
40,25668,Dunhil Attar Strong Fragrance Attar – 10 ML,dunhil-attar-strong-fragrance-attar-10-ml,0,simple,,https://www.omjaa.com/product/dunhil-attar-str...,S03250,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
41,25667,Polo Sport Premium Fragrance Attar – 10 ML,polo-sport-premium-fragrance-attar-10-ml,0,simple,,https://www.omjaa.com/product/polo-sport-premi...,S03249,"<ul>\n<li><span style=""color: #808080""><strong...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
42,25660,Gucci Black Attar Premium Quality Fragrance – ...,gucci-black-attar-premium-quality-fragrance-10-ml,0,simple,,https://www.omjaa.com/product/gucci-black-atta...,S03248,"<ul>\n<li><strong><span style=""font-size: 11px...","<h2 data-thread-perm-id=""thread-f:169102262361...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
43,25655,Mantrit (Energized) Natural Rose Quartz Raw St...,abhimantrit-natural-rose-quartz-raw-stone-1-13...,0,simple,,https://www.omjaa.com/product/abhimantrit-natu...,S03247,"<p>&nbsp;</p>\n<ul>\n<li><span style=""color: #...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
44,25649,Mantrit (Energized) Natural Rose Quartz Raw St...,abhimantrit-natural-rose-quartz-raw-stone-818-...,0,simple,,https://www.omjaa.com/product/abhimantrit-natu...,S03246,"<p>&nbsp;</p>\n<ul>\n<li><span style=""color: #...","<h1 class=""title style-scope ytd-video-primary...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
45,25580,Mantrit (Energized) 11 Mukhi (Nepali) Rudraksh...,abhimantrit-11-mukhi-nepali-rudraksha-bead-aff...,0,simple,,https://www.omjaa.com/product/abhimantrit-11-m...,S03245,"<ul>\n<li><span style=""color: #808080;font-siz...","<p><strong><span style=""font-size: 18px;color:...",...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
46,25572,Mantrit (Energized) Original Adjustable Pyrite...,abhimantrit-original-pyrite-ring-with-authenti...,0,simple,,https://www.omjaa.com/product/abhimantrit-orig...,S03244,"<ul>\n<li><span style=""font-size: 11px;color: ...",<h2>Abhimantrit Original Adjustable Pyrite Rin...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
47,25558,Mantrit (Energized) Original Adjustable Sulema...,abhimantrit-original-sulemani-hakik-stone-ring...,0,simple,,https://www.omjaa.com/product/abhimantrit-orig...,S03242,"<ul>\n<li><span style=""font-size: 11px;color: ...",<h2>Abhimantrit Original Adjustable Sulemani H...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
48,25552,Mantrit (Energized) Black Tourmaline Jewellery...,abhimantrit-black-tourmaline-jewellery-set-rin...,0,simple,,https://www.omjaa.com/product/abhimantrit-blac...,S03241,"<ul>\n<li><span style=""font-size: 11px;color: ...",<h2>Abhimantrit Black Tourmaline Ring With Lab...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}
49,25546,Mantrit (Energized) Black Tourmaline Pendent &...,abhimantrit-black-tourmaline-pendent-earrings-...,0,simple,,https://www.omjaa.com/product/abhimantrit-blac...,S03240,"<ul>\n<li><span style=""font-size: 11px;color: ...",<h2>Abhimantrit Black Tourmaline Ring With Lab...,...,[],[],False,True,True,False,None,False,"{'text': 'Add to cart', 'description': 'Add &l...",{}

In [47]:
#Save Raw Data
#Create a raw dataset.
#df.to_csv("Desktop/practice/ecommerce-data-pipeline/data/raw_products.csv",index =False)
df.to_csv("data/raw_products1.csv",index =False)

In [48]:
import os
# Note:exist_ok=True means it won't raise an error if the folder already exists.
os.makedirs("data", exist_ok=True)

df.to_csv("data/raw_products.csv", index=False)

In [35]:
#Data Understanding
#How many products?
#How many categories?
#Which columns contain nulls?
#Which columns contain prices?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   50 non-null     int64
 1   name                 50 non-null     object
 2   slug                 50 non-null     object
 3   parent               50 non-null     int64
 4   type                 50 non-null     object
 5   variation            50 non-null     object
 6   permalink            50 non-null     object
 7   sku                  50 non-null     object
 8   short_description    50 non-null     object
 9   description          50 non-null     object
 10  on_sale              50 non-null     bool
 11  prices               50 non-null     object
 12  price_html           50 non-null     object
 13  average_rating       50 non-null     object
 14  review_count         50 non-null     int64
 15  images               50 non-null     object
 16  categories           50 non-null     object
 17  tags                 50 non-null     object
 18  attributes           50 non-null     object
 19  variations           50 non-null     object
 20  has_options          50 non-null     bool
 21  is_purchasable       50 non-null     bool
 22  is_in_stock          50 non-null     bool
 23  is_on_backorder      50 non-null     bool
 24  low_stock_remaining  0 non-null      object
 25  sold_individually    50 non-null     bool
 26  add_to_cart          50 non-null     object
 27  extensions           50 non-null     object
dtypes: bool(6), int64(3), object(19)
memory usage: 9.0+ KB

In [36]:
df.describe()

                id  parent  review_count
count     50.00000    50.0     50.000000
mean   26011.12000     0.0      0.020000
std      331.86324     0.0      0.141421
min    25546.00000     0.0      0.000000
25%    25675.25000     0.0      0.000000
50%    26018.00000     0.0      0.000000
75%    26360.75000     0.0      0.000000
max    26574.00000     0.0      1.000000

In [49]:
df.columns

Index(['id', 'name', 'slug', 'parent', 'type', 'variation', 'permalink', 'sku',
       'short_description', 'description', 'on_sale', 'prices', 'price_html',
       'average_rating', 'review_count', 'images', 'categories', 'tags',
       'attributes', 'variations', 'has_options', 'is_purchasable',
       'is_in_stock', 'is_on_backorder', 'low_stock_remaining',
       'sold_individually', 'add_to_cart', 'extensions'],
      dtype='object')

In [10]:
df.isnull().sum()

id                      0
name                    0
slug                    0
parent                  0
type                    0
variation               0
permalink               0
sku                     0
short_description       0
description             0
on_sale                 0
prices                  0
price_html              0
average_rating          0
review_count            0
images                  0
categories              0
tags                    0
attributes              0
variations              0
has_options             0
is_purchasable          0
is_in_stock             0
is_on_backorder         0
low_stock_remaining    50
sold_individually       0
add_to_cart             0
extensions              0
dtype: int64

In [38]:
# Note it is onlt for learn perpose
# 1.Data Cleaning :it is only select the required column and remainging skip
# selected_cols = [
#     "id",
#     "name",
#     "prices",
#     "price_html"
# ]
# df = df[selected_cols

# 2. To check column name present or not in dataframe
#print(df.columns.tolist())
#or
# df.columns
# #3. Remane the column
# df.columns =[
#     "product_name",
#      "product_id",
#     "sale_price",
#     "regular_prices"
    
# ]

In [50]:
#Create new columns from the nested dictionary:

df = df.copy()

df["sale_price"] = df["prices"].apply(
    lambda x: x.get("price") if isinstance(x, dict) else None
)

df["regular_price"] = df["prices"].apply(
    lambda x: x.get("regular_price") if isinstance(x, dict) else None
)

In [51]:
#Now select useful columns:
selected_cols = [
    "id",
    "name",
    "sale_price",
    "regular_price"
]

df = df[selected_cols].copy()

In [52]:
#Rename columns:

df.columns = [
    "product_id",
    "product_name",
    "sale_price",
    "regular_price"
]

In [53]:
#Feature Engineering
#Convert prices to numeric:

import pandas as pd

df["sale_price"] = pd.to_numeric(
    df["sale_price"],
    errors="coerce"
)

df["regular_price"] = pd.to_numeric(
    df["regular_price"],
    errors="coerce"
)

In [54]:
#Create Discount:

df["discount"] = (
    df["regular_price"]
    - df["sale_price"]
)

In [55]:
#Create Discount Percentage:

df["discount_percentage"] = (
    df["discount"]
    / df["regular_price"]
) * 100

In [56]:
#Save Clean Data
#First create the folder if it doesn't exist:
import os

os.makedirs("output", exist_ok=True)

In [57]:
 # Then save
df.to_csv(
    "output/clean_products.csv",
    index=False
)

In [58]:
print(df.head())

   product_id                                       product_name  sale_price  \
0       26574  Mantrit (Energized) Parad Goli, Original &#038...       96000
1       26528  Mantrit Vastu Brass Brahmasthan Plate with 9 P...      955100
2       26518  Mantrit Brass Manjusha Box for Vastu – Treasur...      285100
3       26511  Mantrit Brass Nabhi Set for Vastu Correction &...      275100
4       26480  Natural Amethyst Crystal Cave (28.7 Kg) – 15 I...     9510000

   regular_price  discount  discount_percentage
0         148000     52000            35.135135
1        1355100    400000            29.518117
2         495100    210000            42.415674
3         490000    214900            43.857143
4       15500000   5990000            38.645161

In [60]:
df

,product_id,product_name,sale_price,regular_price,discount,discount_percentage
0,26574,"Mantrit (Energized) Parad Goli, Original &#038...",96000,148000,52000,35.135135
1,26528,Mantrit Vastu Brass Brahmasthan Plate with 9 P...,955100,1355100,400000,29.518117
2,26518,Mantrit Brass Manjusha Box for Vastu – Treasur...,285100,495100,210000,42.415674
3,26511,Mantrit Brass Nabhi Set for Vastu Correction &...,275100,490000,214900,43.857143
4,26480,Natural Amethyst Crystal Cave (28.7 Kg) – 15 I...,9510000,15500000,5990000,38.645161
5,26450,Mantrit 4 Mukhi Rudraksha Nepali 28mm Rare Bea...,360000,460000,100000,21.739130
6,26408,Mantrit Rose Quartz Ducks &#8211; 89 Gram | Lo...,220000,340000,120000,35.294118
7,26402,Mantrit Rose Quartz Ducks &#8211; 107 Gram | L...,265000,540000,275000,50.925926
8,26393,Natural Raw Moonstone Chunks – Rough Healing C...,195000,285000,90000,31.578947
9,26391,Product,0,0,0,NaN
10,26389,Product,0,0,0,NaN
11,26374,Original Tiger Eye Shivling Mantrit (Energized...,300000,420000,120000,28.571429
12,26364,Genuine Labradorite Hanuman ji Idol Mantrit (E...,1175000,1750000,575000,32.857143
13,26351,Mantrit 5 Mukhi Rudraksha Kanthi Mala 54+1 Bea...,260000,460000,200000,43.478261
14,26330,Mantrit 5 Mukhi Rudraksha (Nepali) Big Rare Be...,360000,450000,90000,20.000000
15,26277,Karungali Mala (Ebony Wood Mala) – Natural Bla...,75000,110000,35000,31.818182
16,26126,Original Big Green Aventurine Raw Stone &#8211...,245000,320000,75000,23.437500
17,26117,Certified Moonstone Bracelet – Embrace Serenit...,145000,185000,40000,21.621622
18,26098,Mantrit Pyrite Frame with Gayatri Mantra – Ele...,185000,230000,45000,19.565217
19,26091,Natural Chandra Mani (Mukta Mani) 25 Carat in ...,450000,570000,120000,21.052632
20,26085,Natural Chandra Mani (Mukta Mani) 30 Carat in ...,520000,650000,130000,20.000000
21,26079,"Natural Ganesh Shankh 8cm Approx – Mantrit , G...",125000,175000,50000,28.571429
22,26064,Authentic Golden White Shukra Mani Abhimantrit...,1060000,1270000,210000,16.535433
23,26043,Triangle Pyrite Frame 9 Inch for Home Decor &#...,145000,185000,40000,21.621622
24,26025,Original Cinnamon Essential Oil (Dalchini Tel)...,35100,75000,39900,53.200000
25,26011,Very Rare Nepali 5 Mukhi Rudraksha Mala Origin...,650000,980000,330000,33.673469
26,26000,Mach Mani (Fish Pearl) &#038; Abhimantrit Natu...,650000,850000,200000,23.529412
27,25924,Certified Supreme Quality Golden Pyrite Raw St...,490000,610000,120000,19.672131
28,25923,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,59900,85000,25100,29.529412
29,25922,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,46000,55000,9000,16.363636
30,25914,Natural Cow Dung Dhoop | Cow Dung Havan Cups |...,26000,36000,10000,27.777778
31,25791,Original Zibu Coin Bracelet With Multi Stone P...,95100,150000,54900,36.600000
32,25735,Lab -Certified Natural Green Aventurine 5.25 c...,160000,600000,440000,73.333333
33,25696,Mantrit (Energized) Vastu Maha Yantra,65100,150000,84900,56.600000
34,25693,Mantrit (Energized) Sarva Badha Nivaran Yantra,45100,150000,104900,69.933333
35,25678,Nature And Original Camphor (Kapoor) Oil – 10 ML,45000,120000,75000,62.500000
36,25676,X Chocolate Attar Fragrance Attar – 10 ML,45000,120000,75000,62.500000
37,25675,Dior Premium Quality Fragrance Attar – 10 ML,45000,120000,75000,62.500000
38,25673,Cigar Fragrance Attar – 10 ML,45000,120000,75000,62.500000
39,25670,Golden Dust Fragrance Attar For Gold Personali...,45000,120000,75000,62.500000
40,25668,Dunhil Attar Strong Fragrance Attar – 10 ML,45000,120000,75000,62.500000
41,25667,Polo Sport Premium Fragrance Attar – 10 ML,45000,120000,75000,62.500000
42,25660,Gucci Black Attar Premium Quality Fragrance – ...,45000,120000,75000,62.500000
43,25655,Mantrit (Energized) Natural Rose Quartz Raw St...,220000,420000,200000,47.619048
44,25649,Mantrit (Energized) Natural Rose Quartz Raw St...,175100,340000,164900,48.500000
45,25580,Mantrit (Energized) 11 Mukhi (Nepali) Rudraksh...,810000,1500000,690000,46.000000
46,25572,Mantrit (Energized) Original Adjustable Pyrite...,110000,250000,140000,56.000000
47,25558,Mantrit (Energized) Original Adjustable Sulema...,110000,250000,140000,56.000000
48,25552,Mantrit (Energized) Black Tourmaline Jewellery...,210000,375100,165100,44.014929
49,25546,Mantrit (Energized) Black Tourmaline Pendent &...,135100,250000,114900,45.960000